### PR TITLE
fixed a bug on parsing NSKeyedArchive plists

### PR DESCRIPTION
**Pull request by aymenim**

### CODE REVIEW

**Comment by lcfr123** [comment]
I've tried it, and the backup that had files that failed to decrypt now seems to decrypt those correctly.

**Comment by lcfr123** [comment]
Alas, almost... There seem two be two problems left, in backup10.py:

1) When the flags retrieved from Manifest.db records contain '16'. Domain, relative_path and file_blob are 'None'. Then MBFile() crashes.
2) A large number of 'WARNING: Cannot unwrap key' messages.

Any ideas on these points?

**Comment by dinosec** [comment]
Thanks for the contribution and sorry about the delay merging this pull request.

**Comment by lcfr123** [comment]
No problem! I just added pull request #15, to complete this patch.

**Pull request merged**
