### PR TITLE
backup_tool: added support for iOS 10 encrypted backups

### PR DESCRIPTION
**Pull request by aymenim**

### CODE REVIEW

**Comment by dinosec** [comment]
Thanks!

**Comment by lcfr123** [comment]
I've tried it on my backup, and it doesn't seem to work? iOS 10.1.1 with iTunes 12.5.3.17. The files are extracted, no errors are given, but the data still looks encrypted...

**Comment by aymenim** [comment]
Checked it again, it doesn't work for some files the problem seems to be the NSKeyedArchive from the blob in Manifest.db, does not have the same structure for all entries when opened as a plist, need to find a proper way of parsing the NSKeyedArchive serialized data.

**Comment by aymenim** [comment]
@lcfr123 please check the new pull request #12 if it decrypts properly for you

**Comment by lcfr123** [comment]
Yes, it decrypts it now. Thank you very much!

**Pull request merged**
